### ISSUE TITLE
Publish on pub.dartlang.org

### ISSUE THREAD

**Issue by adaojunior** [emilniklas/chalk#1]
Hi, do you plan to publish this on pub.dartlang.org ?

**Comment by emilniklas** [comment]
When I started working on this, I realized I was doing a lot of work that could be generalized. So I stopped and did this project: https://github.com/dart-embla/template_cache

Later I never got around to make an actual Chalk implementation of the compiler that is required. I'm afraid this project simply isn't done, and probably won't be finished in the foreseeable future. I'm sorry. 😢 

If you want a fun project for yourself, you could make your own compiler. The entire foundation for that is in the template_cache project.

``` dart
import 'dart:async';
import 'package:template_cache/cache.dart';

class YOURCompiler implements Compiler {
  final ContentType contentType = ContentType.HTML;
  final Iterable<String> extensions = ['.YOUR_ext', '.YOUR_other_ext'];

  Future<GeneratedTemplateCode> compile(Uri file, Stream<String> source) async {
    // Use the [file] and [source] arguments to generate the code

    return new GeneratedTemplateCode(
      '''
        import "any_imports_that_the_template_runtime_will_need";
      ''',

      r'''
        yield r"A line!\n";

        yield someLocal + r'\n';

        // the generated code is in an async* context, so you can await
        await someImportedFunction();

        if (someBooleanLocal) {
          yield r"A conditional line!\n";
        }
      '''
    );
  }
}
```
